# Generated by Django 5.2.15 on 2026-07-04 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='produits/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categorie')),
            ],
        ),
    ]
