# Generated by Django 5.2.15 on 2026-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
