# Generated by Django 5.0.3 on 2026-07-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
